export const NAV_LABELS = ["About Us", "Services", "Contact", "Projects"];
export const TAG_LINE = "You Innovate. We Navigate.";
export const NORB_PHARMA = "Norb Pharma";
export const service1 = "Scientific office and drug store establishment.";
export const service2 = "Registration of medical products or devices with EDE or municipal authorities";
export const service3 = "Supply of chemicals,reagents,and reference standards";
export const service4 = "Method of Analysis (MOA) development";
export const PHONE_NO = "+971-50-2703654";
export const LINKEDIN = "https://www.linkedin.com/company/norb-pharma/";
export const address = "Al Barsha - Al Barsha South - floor 13 - Dubai";
export const MAP_LOCATION = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3613.807146583992!2d55.23696957394338!3d25.074524836661265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f6e9034646427%3A0x7c729bc533076999!2sDubai%20Science%20Park%20Towers!5e0!3m2!1sen!2sae!4v1755171034164!5m2!1sen!2sae";
export const vision = "Our vision is to be the definitive regulatory partner that transforms complex compliance challenges into streamlined pathways tosuccess. We don't just navigate the registration process— we master it,ensuring every medical device, pharmaceutical product, drugstore, and scientific office establishment moves from concept to market authorization with unparalleled precision and efficiency.";
export const landing_page_1 = "Your regulatory partner, turning compliance into success.";
export const landing_page_2 = "Seamless Regulatory Compliance for Medical Devices & Pharmaceuticals";
export const landing_page_3 = "Norb stands as your trusted partner in healthcare advancement— where experience meets innovation, and regulatory success is not just a promised, but delivered.";
export const landing_page_4 = "Your Innovation. Our Expertise. Seamless Results.";
export const hero_heading = "Seamless Regulatory Compliance for Medical Devices & Pharmaceuticals";